# Generated by Django 3.2.23 on 2024-10-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    def load_fixture(apps, schema_editor):
        from django.core.management import call_command
        call_command('load_fuel_data_from_cached_file')

    operations = [
        migrations.CreateModel(
            name="FuelStation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ("station_id", models.IntegerField()),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=2)),
                ("rack_id", models.IntegerField()),
                ("retail_price", models.DecimalField(decimal_places=3, max_digits=6)),
                (
                    "latitude",
                    models.DecimalField(decimal_places=6, max_digits=9, null=True),
                ),
                (
                    "longitude",
                    models.DecimalField(decimal_places=6, max_digits=9, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "fuel_stations",
            },
        ),
        migrations.AddIndex(
            model_name="fuelstation",
            index=models.Index(
                fields=["station_id"], name="fuel_statio_station_07f62e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fuelstation",
            index=models.Index(
                fields=["latitude", "longitude"], name="fuel_statio_latitud_c84538_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fuelstation",
            index=models.Index(fields=["state"], name="fuel_statio_state_db56e5_idx"),
        ),
        migrations.RunPython(load_fixture),
    ]
